### ISSUE TITLE
ntpdsigndsocket option missing

### ISSUE THREAD

**Issue by phantomdez** [voxpupuli/puppet-chrony#107]
This is more of a feature request.

The parameter ntpsigndsocket  is not available.  This option is typically used in samba environments and would be helpful to add to the configuration.

Similar functionality has been added to NTP:
ntpsigndsocket
Data type: Optional[Stdlib::Absolutepath]

Sets NTP to sign packets using the socket in the ntpsigndsocket path. Requires NTP to be configured to sign sockets. Value: Path to the socket directory; for example, for Samba: usr/local/samba/var/lib/ntp_signd/. Default value: undef.

**Comment by alexjfisher** [comment]
Would you be able to create a Pull Request that adds this functionality?

**Comment by phantomdez** [comment]
Just learning this stuff so I am a bit of a newbie.  Not sure how to do that yet.
