### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by unixsurfer** [voxpupuli/puppet-chrony#115]
When are you planning to make a new release? It will be very convenient for me if you emit a new release after merging https://github.com/voxpupuli/puppet-chrony/pull/113 and https://github.com/voxpupuli/puppet-chrony/pull/112.

**Comment by jasonknudsen** [comment]
Would very much appreciate if we could also get https://github.com/voxpupuli/puppet-chrony/pull/110 merged into the new release as well? Looks like you've made some promising progress fixing the tests. Appreciate all your efforts! Thanks.

**Comment by jasonknudsen** [comment]
Also tossed this one up here, its another option we've been using in our fork: https://github.com/voxpupuli/puppet-chrony/pull/116 thanks so much!
