### ISSUE TITLE
A number of config options are missing

### ISSUE THREAD

**Issue by kendall-moore** [voxpupuli/puppet-chrony#121]
When attempting to manage chrony I noticed there are many valid config options that are missing. Namely,

  * allow
  * logchange
  * minsamples
  * minsources

My suspicion is that there are others. I'd like to make a PR to address at least these items though I think it's worth looking into adding a parameter such as `chrony::config_extras` or something similar where a user could pass key/value pairs directly into the resulting `chrony.yaml`

PR to follow adding class params for the 4 mentioned above.

**Comment by ripienaar** [comment]
`acquisitionport` is also missing, without which it's pretty much impossible to securely configre this like other ntp servers.
