### ISSUE TITLE
prefer option for server

### ISSUE THREAD

**Issue by baragoon** [voxpupuli/puppet-chrony#199]
Hi,
is it possible to add "prefer" option for the specific server?
Can't find any available option for this.
Thank you in advance!

**Comment by kenyon** [comment]
Yes, you add options as an array like in the example here: https://github.com/voxpupuli/puppet-chrony?tab=readme-ov-file#id-like-to-use-ntp-authentication

**Comment by baragoon** [comment]
> Yes, you add options as an array like in the example here: https://github.com/voxpupuli/puppet-chrony?tab=readme-ov-file#id-like-to-use-ntp-authentication

Hi, thank you for your answer!
But, is there any chance to do this through hiera?

**Comment by kenyon** [comment]
Yes, you can do this through hiera.
