### ISSUE TITLE
avoid changing configuration when adding optional parameters

### ISSUE THREAD

**Issue by vchepkov** [voxpupuli/puppet-chrony#64]
Currently, with each new managed parameter, configuration file gets new 'hanging' comments and empty lines, for example:
```
# Hardware reference clock drivers


# https://chrony.tuxfamily.org/doc/3.4/chrony.conf.html#leapsecmode

# https://chrony.tuxfamily.org/doc/3.4/chrony.conf.html#maxslewrate

# https://chrony.tuxfamily.org/doc/3.4/chrony.conf.html#smoothtime

```

Conditionals in the template should encompass optional comments and not to add empty lines, causing unnecessary global service restart

**Comment by ekohl** [comment]
I think #79 changed the line endings to be more consistent. Mind checking if this is still an issue for you?

**Comment by vchepkov** [comment]
Yes, template is great now!
