### ISSUE TITLE
Consolidate templates

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-chrony#67]
I've noticed that the chrony.conf.redhat.erb and chrony.conf.debian.erb are the exact same file and chrony.conf.archlinux.erb is missing several options.

I think it would make sense to have just a single template (epp whilst we're at it).

**Comment by aboe76** [comment]
@alexjfisher that would be a better solution, at first the idea was to have them separated and nicely formatted the way the distro's provided the default files. 

But considering the multiple extra params now I think it would be better to have the module provide the config file with all the managed parameters.

**Comment by chrekh** [comment]
I have made a attempt at doing this. #79
