### ISSUE TITLE
Migration to Vox Pupuli

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-chrony#69]
- [x] @aboe76 to migrate github repository to voxpupuli
- [x] Update metadata.json https://github.com/voxpupuli/puppet-chrony/pull/71
- [x] Plumbing PR and travis secret generation https://github.com/voxpupuli/plumbing/pull/231
- [x] modulesync_config PR
- [x] Modulesync
- [x] Perform label sync
- [x] Update Readme acknowledging migration to Vox https://github.com/voxpupuli/puppet-chrony/pull/71
- [x] Create release summary ticket https://github.com/voxpupuli/puppet-chrony/issues/70
- [x] Fix badges https://github.com/voxpupuli/puppet-chrony/pull/71
- [x] Move existing Changelog to HISTORY.MD and setup for github-changelog-generator
- [x] Perform first release
- [x] Deprecate old module (via JIRA ticket or API call by @aboe76)

**Comment by aboe76** [comment]
@alexjfisher transfered the repo

**Comment by alexjfisher** [comment]
I don't want to do a modulesync if that means removing pdk from this module.  Instead, I'm looking forward to the results of https://github.com/voxpupuli/pdksync_config/issues/1

@logicminds How close are we to being able to add this module to https://github.com/voxpupuli/pdksync_config/blob/8f9a0b83bfa8cd75a09d6181659e7c844572d736/managed_modules.yml?

**Comment by alexjfisher** [comment]
@aboe76 Would you be really upset if we at least temporarily de-pdked this module?  I was really hoping we'd have a pdk based workflow working properly at Vox by now, but it's been *months* and at this point I'd prefer to just get things moving again through our well trodden modulesync based release process.

**Comment by aboe76** [comment]
@alexjfisher I won't be upset, Do you need me to do something?

**Comment by igalic** [comment]
> @aboe76 Would you be really upset if we at least temporarily de-pdked this module? I was really hoping we'd have a pdk based workflow working properly at Vox by now, but it's been _months_ and at this point I'd prefer to just get things moving again through our well trodden modulesync based release process.

@alexjfisher do we have a roadmap / issue tracking what needs to happen before we can jump on the pdk train?

**Comment by logicminds** [comment]
Nothing stopping us from using pdk here.  Just need to point pdk to our templates instead

**Comment by logicminds** [comment]
I wrote up some docs on how to do this.  

https://github.com/voxpupuli/pdk-templates/blob/vp-latest/VP_README.md#converting-a-module

This would be the second module converted to vox pupuli pdk format so there is likely the need to update some procedures.
Will also need to add the module here: https://github.com/voxpupuli/pdksync_config/blob/8f9a0b83bfa8cd75a09d6181659e7c844572d736/managed_modules.yml

**Comment by aboe76** [comment]
> > @aboe76 Would you be really upset if we at least temporarily de-pdked this module? I was really hoping we'd have a pdk based workflow working properly at Vox by now, but it's been _months_ and at this point I'd prefer to just get things moving again through our well trodden modulesync based release process.
> 
> @alexjfisher do we have a roadmap / issue tracking what needs to happen before we can jump on the pdk train?

I don't mind de-pdked the module if that helps.

**Comment by alexjfisher** [comment]
https://forge.puppet.com/puppet/chrony :)

@aboe76 I'm really sorry it took so long.  Would you like to [deprecate](https://forgeapi.puppet.com/?_ga=2.69307027.2065595814.1603627772-1168419750.1557417093#operation/deprecateModule) the aboe/chrony?

**Comment by aboe76** [comment]
done via jira:
https://tickets.puppetlabs.com/secure/RapidBoard.jspa?rapidView=1220&projectKey=FORGE&view=detail&selectedIssue=FORGE-564
