### ISSUE TITLE
Release Summary for 0.4.0

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-chrony#70]
This is the first release of this module under [Vox Pupuli](https://voxpupuli.org/)'s [puppet](https://forge.puppet.com/puppet) namespace.  It was migrated to Vox Pupuli from [oboe76/chrony](https://forge.puppet.com/oboe76/chrony).

**Comment by vchepkov** [comment]
Seems module got forgotten. Any plan to release new voxpupuli version?

**Comment by alexjfisher** [comment]
yes... it got delayed whilst we got confused as to what the plan with pdk was.  There might be movement soon though. https://github.com/voxpupuli/pdk-templates/issues/1#issuecomment-713176646
