### ISSUE TITLE
Are we creating a invalid keyfile?

### ISSUE THREAD

**Issue by chrekh** [voxpupuli/puppet-chrony#91]
I just noticed that chrony.conf(5) states the following about the keyfile

```
Each line consists of an ID, name of an authentication hash function (optional), and a
password. The ID can be any unsigned integer in the range 1 through 2^32-1. The default
hash function is MD5, which is always supported.
```

But we are creating a keyfile with ID=0 default. Is that a problem?

**Comment by alexjfisher** [comment]
I think it would have been valid in chrony 2.1???
https://chrony.tuxfamily.org/doc/2.1/manual.html#keyfile-directive

Does `chrony_password` need to go away too?
https://chrony.tuxfamily.org/faq.html#_what_happened_to_the_code_commandkey_code_and_code_generatecommandkey_code_directives

You'd need to double check, but I'm not sure we have any OSes we want to support that ship with such an old version.

**Comment by chrekh** [comment]
Thanks, I suppose since chrony doesn't complain or fail when we have the key ID=0 it's probably best to leave it as it is.
